#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORTING_FETCH_MODE_STATE_OF_CHARGE=y

CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=7200000

##for NiMH battery
CONFIG_ZMK_NON_LIPO_BATTERY_MANAGEMENT=y

# optional
CONFIG_ZMK_NON_LIPO_MAX_MV=1360
CONFIG_ZMK_NON_LIPO_MIN_MV=1020
CONFIG_ZMK_NON_LIPO_LOW_MV=1000
#CONFIG_ZMK_NON_LIPO_ADV_SLEEP_TIMEOUT=60000
# 60 seconds